# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python --version  # Debugging check
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip setuptools wheel  # Upgrade core tools
        pip install --no-cache-dir flake8 pytest  # Avoid using cached packages
        if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
    - name: Lint with flake8
      run: |
          source venv/bin/activate
          pip install --no-cache-dir flake8  # Ensure flake8 is installed
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     
    - name: Test with pytest
      run: |
          source venv/bin/activate
          pip install --no-cache-dir pytest  # Ensure pytest is installed
          pytest --disable-warnings
     
